In [8]:
import cv2
import numpy as np

In [16]:
class CVNumber:
    
    def __init__(self, value):
        self.value = value    
    
    def __add__(self, other):
        return cv2.add(self.value, other.value) 
    
    def __sub__(self, other):
        return cv2.add(self.value, -other.value) 
    
    def __mul__(self, other):
        pass
    
    def __rmul__(self, other):
        pass
    
    def __div__(self, other):
        pass
    
    def __rdiv__(self, other):
        pass

In [17]:
x = np.uint8([250])
y = np.uint8([10])

In [18]:
x = CVNumber(x)
y = CVNumber(y)

In [19]:
x.value

array([250], dtype=uint8)

In [14]:
y.value

array([10], dtype=uint8)

In [20]:
x + y

array([[255]], dtype=uint8)

In [ ]:
cv2.add()